;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Fri May 30 2025
; Processor: PIC16F877A
; Compiler:  MPASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

#include p16f877a.inc                ; Include register definition file

;====================================================================
; VARIABLES
;====================================================================
CBLOCK 0x20
INREG       ; Holds the input number
INDEX       ; Loop index
TEMP        ; Temp value
PBASE       ; Address of the first prime (PRIME0)
PRIME0
PRIME1
PRIME2
PRIME3
PRIME4
PRIME5
TEMP1
msd
lsd
PRIMEFLAG
CURRENTRANGE
ADCVALUE
LASTSTATE 
index           
correctAnswer   
userAnswer      
timer
DCounter1
DCounter2
DCounter3 
challengeOneflag
seed            
        ENDC
;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================
;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
RST   code  0x0 
      goto  Start

;====================================================================
; CODE SEGMENT
;====================================================================

PGM   code


      ; Reset Vector

Start
      CALL intitial
	  CALL LOAD_PRIMES
	  CALL initLCD
      ; Write your code here
Loop  
loopflag1
      CALL readPortB
      CALL challengeOne
      MOVF PRIMEFLAG, W
      BTFSC STATUS, Z
      goto loopflag1
      CALL read_adc_value
	  
      CALL check_range_challenge
      call challengethree
      finish goto finish



	
      goto  Loop

;====================================================================
challengethree:
      
      MOVLW 9
      MOVWF timer
LOOP1  
      BTFSC PORTB , 0
      GOTO LOOP1
      movlw 0x01
      call send_cmd
      movf ADCVALUE,w
      movwf seed
      rrf seed , F 
      rrf seed, F 
      rrf seed, F 
      xorwf seed , F 
      
      mod6 
      movlw d'5' 
      subwf seed,F 
      btfsc STATUS , C 
      goto mod6
      movlw 0x05
      andwf seed ,f
      movf seed , w
      CALL display_problem
      movwf correctAnswer 
loop7seg
      MOVF timer , W
      CALL display7Seg
      CALL DELAY1sec
      decf timer , f
      BTFSc PORTB , 1
      goto loop7seg
      call readPortB
      xorwf correctAnswer
      btfsc STATUS , Z
      call show_win
      btfss STATUS , Z
      call send_hard_luck_message
      return
send_hard_luck_message:
   movlw 0x01
   call send_cmd
    movlw 'H'
    call send_char
    movlw 'a'
    call send_char
    movlw 'r'
    call send_char
    movlw 'd'
    call send_char
    movlw ' '
    call send_char
    movlw 'L'
    call send_char
    movlw 'u'
    call send_char
    movlw 'c'
    call send_char
    movlw 'k'
    call send_char
    return
show_win:
   movlw 0x01
   call send_cmd
   movlw 'Y'
    call send_char
    movlw 'O'
    call send_char
    movlw 'U'
    call send_char
    movlw ' '
    call send_char
    movlw 'W'
    call send_char
    movlw 'I'
    call send_char
    movlw 'N'
    call send_char
    movlw '!'
    call send_char
    movlw ' '
    call send_char
    movlw 'E'
    call send_char
    movlw 's'
    call send_char
    movlw 'c'
    call send_char
    movlw 'a'
    call send_char
    movlw 'p'
    call send_char
    movlw 'e'
    call send_char
    movlw 0x07
    movwf PORTE
    MOVLW 0XFF
    CALL delay
    MOVWF PORTC
    MOVWF 0x00
    MOVLW 0XFF
    CALL delay
    MOVWF PORTC
    MOVWF 0x00
    return
display_problem:
    addwf   PCL, f
    goto    problem0
    goto    problem1
    goto    problem2
    goto    problem3
    goto    problem4

; ----------------------------------
problem0:
    movlw '2'
    call send_char
    movlw '+'
    call send_char
    movlw '3'
    call send_char
    movlw '='
    call send_char
    movlw '?'
    call send_char
    movlw 5      ; Answer in WREG
    return

problem1:
    movlw '7'
    call send_char
    movlw '-'
    call send_char
    movlw '2'
    call send_char
    movlw '='
    call send_char
    movlw '?'
    call send_char
    movlw 5
    return

problem2:
    movlw '4'
    call send_char
    movlw '+'
    call send_char
    movlw '5'
    call send_char
    movlw '='
    call send_char
    movlw '?'
    call send_char
    movlw 9
    return

problem3:
    movlw '6'
    call send_char
    movlw '-'
    call send_char
    movlw '3'
    call send_char
    movlw '='
    call send_char
    movlw '?'
    call send_char
    movlw 3
    return

problem4:
    movlw '1'
    call send_char
    movlw '+'
    call send_char
    movlw '6'
    call send_char
    movlw '='
    call send_char
    movlw '?'
    call send_char
    movlw 7
    return


display7Seg:
    ; WREG has the number (0-9)
    ; Add offset to PCL for computed jump
    addwf   PCL, f

    goto    seg_0
    goto    seg_1
    goto    seg_2
    goto    seg_3
    goto    seg_4
    goto    seg_5
    goto    seg_6
    goto    seg_7
    goto    seg_8
    goto    seg_9

seg_0:
    movlw   0x40
    goto    write_seg

seg_1:
    movlw   0x79
    goto    write_seg

seg_2:
    movlw   0x24
    goto    write_seg

seg_3:
    movlw   0x30
    goto    write_seg

seg_4:
    movlw   0x19
    goto    write_seg

seg_5:
    movlw   0x12
    goto    write_seg

seg_6:
    movlw   0x02
    goto    write_seg

seg_7:
    movlw   0x78
    goto    write_seg

seg_8:
    movlw   0x00
    goto    write_seg

seg_9:
    movlw   0x10

write_seg:
    movwf   PORTC
    return
intitial:
      ; Set TRISB = 0xFF (PORTB as input)
        BSF STATUS, RP0       ; Switch to Bank 1
        BCF STATUS, RP1
        MOVLW 0xFF
        MOVWF TRISB
		
        ; Set TRISC = 0x00 (PORTC as output)
        MOVLW 0x00
        MOVWF TRISC

        ; Set TRISE = 0x00 (PORTE as output)
        MOVLW 0x00
        MOVWF TRISE

        ; Set TRISA = 0x00 (PORTA as output)
        MOVLW 0x00
        MOVWF TRISA

        ; Set TRISD = 0x00 (PORTD as output)
        MOVLW 0x00
        MOVWF TRISD

        ; Set ADCON1 = 0x8E
        MOVLW 0x8E
        MOVWF ADCON1

        ; Return to Bank 0
        BCF STATUS, RP0
	 
        ; Set PORTC = 0xFF (all segments OFF)
        MOVLW 0xFF
        MOVWF PORTC

        ; Set PORTE = 0x00
        MOVLW 0x00
        MOVWF PORTE

        ; Set ADCON0 = 0x41 (ADC on, channel 0)
        MOVLW 0x41
        MOVWF ADCON0

        ; Set PORTA = 0x00
        MOVLW 0x00
        MOVWF PORTA

        ; Set PORTD = 0x00
        MOVLW 0x00
        MOVWF PORTD
       return
readPortB:
      MOVF PORTB , W
      MOVWF TEMP1
      SWAPF TEMP1
      MOVLW 0X0F
      ANDWF TEMP1 , F
      COMF TEMP1
      MOVLW 0X0F
      ANDWF TEMP1 , W
      return
initLCD:

    ; sendLCDCommand(0x38) ; 8-bit mode, 2 lines, 5x7
    MOVLW 0x38
    CALL send_cmd

    ; sendLCDCommand(0x0E) ; Display ON, cursor ON
    MOVLW 0x0E
    CALL send_cmd

    ; sendLCDCommand(0x02) ; Return home
    MOVLW 0x02
    CALL send_cmd

    ; sendLCDCommand(0x01) ; Clear display
    MOVLW 0x01
    CALL send_cmd
    CALL delay

    RETURN
LOAD_PRIMES:
        MOVLW 0x02
        MOVWF PRIME0
        MOVLW 0x03
        MOVWF PRIME1
        MOVLW 0x05
        MOVWF PRIME2
        MOVLW 0x07
        MOVWF PRIME3
        MOVLW 0x0B
        MOVWF PRIME4
        MOVLW 0x0D
        MOVWF PRIME5

        MOVLW 0x24
	MOVWF PBASE
        RETURN

; ===== Function: isPrime =====
; Input: INREG
; Output: Z flag set if prime, cleared if not
isPrime:
    CLRF INDEX           ; INDEX = 0
    CLRF PRIMEFLAG       ; Assume not prime

PrimeLoop:
    ; Compute address: FSR = PBASE + INDEX
    MOVF INDEX, W
    ADDWF PBASE, W
    MOVWF FSR            ; Set FSR to point to PRIME[i]

    ; Compare INREG with PRIME[i]
    MOVF INDF, W         ; W = PRIME[i]
    XORWF INREG, W       ; W = W ^ INREG
    BTFSC STATUS, Z      ; If Z is set, match found
    GOTO PrimeFound

    ; Not found yet, increment INDEX
    INCF INDEX, F
    MOVF INDEX, W
    SUBLW 6              ; Check if INDEX < 6
    BTFSS STATUS, Z      ; If not done, continue loop
    GOTO PrimeLoop

    ; No match found
    RETURN

PrimeFound:
    MOVLW 0x01
    MOVWF PRIMEFLAG      ; Set flag to 1 (true)
    RETURN

; ===== Function: challengeOne =====
; Input: WREG (value to check)
challengeOne:
        MOVWF INREG
        CALL isPrime
	 MOVF PRIMEFLAG, W
	 BTFSC STATUS, Z     ; If PRIMEFLAG = 0 (Z set), not prime
	 GOTO ShowNotPrime
	 GOTO ShowPrime

ShowNotPrime:
        MOVLW 0x06
        MOVWF PORTC
        CLRF PORTE
        RETURN

ShowPrime:
        MOVLW 0x0C
        MOVWF PORTC
        MOVLW 0x01
        MOVWF PORTE
        RETURN       
send_cmd
		movwf	PORTD		; Refer to table 1 on Page 5 for review of this subroutine	
		bcf	PORTA,	1                                                                                 
		bsf	PORTA,	3		
		nop				
		bcf	PORTA,	3
		bcf	PORTA,	2		
		call delay			
		return
		
send_char
		movwf	PORTD		; Refer to table 1 on Page 5 for review of this subroutine	
		bsf	PORTA,	1		 
		bsf	PORTA,	3				
		nop
		bcf	PORTA,	3
		bcf	PORTA,	2
		call delay
		return
		
delay	                                                                                
		movlw	0x40			
		movwf	msd
		clrf	lsd
loop2
		decfsz	lsd,f
		goto	loop2
		decfsz	msd,f
endLcd
		goto	loop2
		return	
send_you_are_correct:
    movlw 0x01
    call send_cmd
    movlw 'Y'
    call send_char
    movlw 'o'
    call send_char
    movlw 'u'
    call send_char
    movlw ' '
    call send_char
    movlw 'a'
    call send_char
    movlw 'r'
    call send_char
    movlw 'e'
    call send_char
    movlw ' '
    call send_char
    movlw 'c'
    call send_char
    movlw 'o'
    call send_char
    movlw 'r'
    call send_char
    movlw 'r'
    call send_char
    movlw 'e'
    call send_char
    movlw 'c'
    call send_char
    movlw 't'
    call send_char
    return
send_you_are_so_close:
    movlw 0x01
    call send_cmd
    movlw 'Y'
    call send_char
    movlw 'o'
    call send_char
    movlw 'u'
    call send_char
    movlw ' '
    call send_char
    movlw 'a'
    call send_char
    movlw 'r'
    call send_char
    movlw 'e'
    call send_char
    movlw ' '
    call send_char
    movlw 's'
    call send_char
    movlw 'o'
    call send_char
    movlw ' '
    call send_char
    movlw 'c'
    call send_char
    movlw 'l'
    call send_char
    movlw 'o'
    call send_char
    movlw 's'
    call send_char
    movlw 'e'
    call send_char
    return
read_adc_value:
    ; Select channel 0
    BANKSEL ADCON0
    MOVLW 0x41
    MOVWF ADCON0
    BCF  STATUS, RP0

    ; Acquisition delay
    CALL delay

    ; Start conversion
    BSF ADCON0, 2

wait_adc:
    BTFSC ADCON0, 2
    GOTO wait_adc

    ; Read result
    BANKSEL ADRESL
    MOVF ADRESL, W
    BCF STATUS,RP0
    MOVWF ADCVALUE   ;CURRENTRANGE ADCVALUE
    RETURN
check_range_challenge:
    ; Set CURRENTRANGE
    MOVF ADCVALUE, W

    SUBLW .51
    BTFSS STATUS, C
    GOTO RANGE2
    MOVLW 1
    MOVWF CURRENTRANGE
    GOTO RANGE_DONE

RANGE2:
    MOVF ADCVALUE, W
    SUBLW .101
    BTFSS STATUS, C
    GOTO RANGE3
    MOVLW 2
    MOVWF CURRENTRANGE
    GOTO RANGE_DONE

RANGE3:
    MOVF ADCVALUE, W
    SUBLW .151
    BTFSS STATUS, C
    GOTO RANGE4
    MOVLW 3
    MOVWF CURRENTRANGE
    GOTO RANGE_DONE

RANGE4:
    MOVF ADCVALUE, W
    SUBLW .201
    BTFSS STATUS, C
    GOTO RANGE5
    MOVLW 4
    MOVWF CURRENTRANGE
    GOTO RANGE_DONE

RANGE5:
    MOVLW 5
    MOVWF CURRENTRANGE

RANGE_DONE:
    ; Now decision logic
    MOVF CURRENTRANGE, W
    MOVWF TEMP
    MOVF LASTSTATE, W

    ; Check if it's range 3
    MOVF CURRENTRANGE, W
    XORLW 3
    BTFSC STATUS, Z
    GOTO ShowCorrect

    ; Check if it's 2 or 4
    MOVF CURRENTRANGE, W
    XORLW 2
    BTFSC STATUS, Z
    GOTO ShowClose
    MOVF CURRENTRANGE, W
    XORLW 4
    BTFSC STATUS, Z
    GOTO ShowClose

    ; Wrong
    MOVF LASTSTATE, W
    BTFSC STATUS, Z
    RETURN
    CALL send_cmd_clear
    CLRF LASTSTATE
    RETURN
ShowCorrect:
    MOVF LASTSTATE, W
    XORLW 1
    BTFSC STATUS, Z
    RETURN
    CALL send_cmd_clear
    CALL send_you_are_correct
    MOVLW 1
    MOVWF LASTSTATE
    MOVLW 0x02
    MOVWF PORTE
    RETURN
ShowClose:
    MOVF LASTSTATE, W
    XORLW 2
    BTFSC STATUS, Z
    RETURN
    CALL send_cmd_clear
    CALL send_you_are_so_close
    MOVLW 2
    MOVWF LASTSTATE
    RETURN
send_cmd_clear:
    MOVLW 0x01
    CALL send_cmd
    RETURN
DELAY1sec

   MOVLW 0Xac
   MOVWF DCounter1
   MOVLW 0X13
   MOVWF DCounter2
   MOVLW 0X06
   MOVWF DCounter3
   LOOPcounter
   DECFSZ DCounter1, 1
   GOTO LOOPcounter
   DECFSZ DCounter2, 1
   GOTO LOOPcounter
   DECFSZ DCounter3, 1
   GOTO LOOPcounter
   NOP
RETURN
      END
